pages:
  image: node:latest
  stage: deploy
  script:
    - npm ci
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public/
  only:
    - gitlab-page
