pages:
  image: node:latest
  stage: deploy
  script:
    - npm ci
    - npm run build 
    - mv public public-vue
    - mv dist public
    - mkdir public/ITI0105-2023-Prototype
    - mv public/assets public/ITI0105-2023-Prototype/assets
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public/
  only:
    - gitlab-page
