version: '3.9'

services:
  flask-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    volumes:
      - ./server:/app 

  mysql-db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: website
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql 

  vue-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - flask-app
      - vue-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
