version: '3.9'

services:
  flask-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db

  mysql-db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  vue-app:
    build:
      context: ./client  
      dockerfile: Dockerfile  
    ports:
      - "5173:5173"  
    
