CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(350) NOT NULL,
    description TEXT NOT NULL,
    image_url VARCHAR(255) NOT NULL
);
